source 'https://rubygems.org'
gem 'rails', '4.2.0'
gem 'pg'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'libv8', '3.16.14.7'
gem 'therubyracer'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'jbuilder', '~> 2.0'
gem 'haml-rails'
gem 'enumerize'
gem 'authority'
gem 'bcrypt', '~> 3.1.7'
gem 'active_form', github: 'rails/actionform', ref: '41ec958'
gem 'simple_form'
gem 'bootstrap-sass'
gem 'bootstrap_glyphicons-rails'
gem 'state_machine', git: 'https://github.com/seuros/state_machine.git'
gem 'draper'
gem 'russian'
gem 'carrierwave'
gem 'mini_magick'
gem 'rmagick'
gem 'datetimepicker-rails', git: 'git://github.com/zpaulovics/datetimepicker-rails.git', branch: 'master', submodules: true
gem 'js-routes'
gem 'i18n-js', git: 'https://github.com/fnando/i18n-js'
gem 'omniauth-google-oauth2'
gem 'omniauth-vkontakte'
gem 'omniauth-twitter'
gem 'omniauth-facebook'
gem 'momentjs-rails', '>= 2.9',  :github => 'derekprior/momentjs-rails'
gem 'awesome_print'
gem 'ckeditor'
gem 'configus'
gem 'foursquare2', github: 'nitinstp23/foursquare2', branch: :gemspec_fix
gem 'validates'
gem 'font-awesome-rails'
gem 'foundation-rails', github: 'zurb/foundation-rails'
gem 'autoprefixer-rails'
gem 'select2-rails'
gem 'bootstrap_flash_messages'
gem 'responders', '~> 2.0'
gem 'to_xls-rails'
gem 'russia_regions'

group :production do
  gem 'unicorn-rails'
end

group :development, :test do
  gem 'byebug'
  gem 'foreman'
  gem 'guard-livereload', '~> 2.4', require: false
  gem 'rack-livereload'
  gem 'web-console', '2.0.0.beta2'
  gem 'spring', '1.3.4'
  gem 'factory_girl_rails'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'capistrano'
  gem 'capistrano-bundler'
  gem 'capistrano-rails'
  gem 'capistrano3-unicorn'
  gem 'capistrano-sidekiq'
  gem 'capistrano-rvm'
  gem 'rvm-capistrano'
  gem 'capistrano-ssh-doctor', '~> 1.0'
  gem 'capistrano-rails-console'
  gem 'capistrano-rails-tail-log'
  gem 'quiet_assets'
  gem 'colorize', '0.6.0'
  gem 'better_errors'
end

group :test do
  gem 'simplecov', require: false
  gem 'tconsole', github: 'ulmic/tconsole', branch: 'rails4'
  gem 'coveralls', require: false
end
